name = "reno-2025"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "reno"

[[kv_namespaces]]
binding = "PHOTO_KV"
id = "296496ddac3f483b8e5e7850825ceb39"

ai = { binding = "AI" }


[site]
bucket = "./public" # Points to your static frontend files
entry-point = "worker" # Tells wrangler where your worker.js is relative to the site
